apiVersion: v1
kind: Pod
metadata:
  name: mavenweb
  labels:
    name: mavenweb
spec:
  containers:
  - name: mavenweb
    image: nagesh447/maven-web:1
    resources:
      requests:
        memory: "100Mi"
        cpu: "200m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080

