apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven
  labels:
    name: mavenhpa 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: maven
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: maven
    spec:
      containers:
      - name: maven
        image: nagesh447/maven-web:1
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 350m
            memory: 320Mi
        ports:
        - containerPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: 
  name: mavenhpascale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mavenhpa
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
    name: memory
    target:
      type: Utilization
      averageUtilization: 60
---
apiVersion: v1
kind: Service
metadata:
  name: mavensvc
spec:
  type: NodePort
  selector:
    app: maven
  ports:
  - port: 80
    targetPort: 8080
