apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven
  namespace: test-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: maven
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: maven
    spec:
      containers:
      - name: maven
        image: nagesh447/maven-web:1
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /maven-web-application
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /maven-web-application
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: mavensvc
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: maven
  ports:
  - port: 80
    targetPort: 8080
