apiVersion: v1
kind: PersistentVolume
metadata: 
  name: nfsw
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 2Gi
  nfs:
    server: 172.31.7.31
    path: /mnt/nfs_share


