apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
  namespace: test-ns
spec:
  hard:
    requests.memory: 256Mi
    requests.cpu: 200m
    limits.memory: 756Mi
    limits.cpu: 800m
    pods: 3
---
apiVersion: v1
kind: LimitRange
metadata:
  name: defaultresource
  namespace: test-ns
spec: 
  limits: 
  - default: 
      cpu: "0.3"
      memory: 350Mi 
    defaultRequest: 
      cpu: 0.1
      memory: 128Mi
    type: Container
