apiVersion: apps/v1
kind: StatefulSet 
metadata:
  name: mongostate
spec:
  serviceName: mongosvc
  replicas: 2
  selector:
    matchLabels:
      app: mongo
  template: 
    metadata:
      labels:
        app: mongo 
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongopod
        image: mongo
        command:
            - "mongod"
            - "--bind_ip"
            - "0.0.0.0"
            - "--replSet"
            - "MainRepSet"
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME 
          value: devdb
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: devdb@123
        volumeMounts:
        - name:  mongovol
          mountPath: /data/db
        resources:
          requests:
            memory: 256Mi
  volumeClaimTemplates:
  - metadata:
      name: mongovol
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 256Gi
---
apiVersion: v1
kind: Service
metadata:
  name:  mongosvc
spec:
  clusterIP: None
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app:  mongo
