apiVersion: v1
kind: ConfigMap
metadata:
  name: tomcatconf
data:
  tomcat-users.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <tomcat-users xmlns="http://tomcat.apache.org/xml"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://tomcat.apache.org/xml tomcat-users.xsd"
            version="1.0">
        <user username="tomcat" password="pass" roles="manager-gui,admin-gui"/>
    </tomcat-users>


